name: AliciaJohnson
favicon: null
layout_spectrum: 0.7309401805978268
typography_spectrum: 0.2704418583307415
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7989459021482617
  lightness: 0.01350253727287054
  saturation: 0.7030623636674136
  rhythmicContrast: 0.8127621205057949
purpose: []
