name: AliciaJohnson
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39212
title: Alicia D. Johnson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7d7a7d'
    - '#000000'
    - '#b2b1ab'
    - '#4c4a51'
    - '#fdfdfa'
  brandStrength: 0.375
  lightness: 0.625
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
