name: AliciaJohnson
favicon: null
layout_spectrum: 0.7309401805978268
typography_spectrum: 0.2704418583307415
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#a9b4ec'
    - '#fffffe'
    - '#6a6cb3'
    - '#019d84'
  brandStrength: 0.7989459021482617
  lightness: 0
  saturation: 0.6875
  rhythmicContrast: 0.8127621205057949
purpose: []
